# Base image
FROM node:20.15-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Run migrations
RUN node ace migration:run

# Expose the port
EXPOSE 3333

# Start the app
CMD ["npm", "run", "dev"]
